demosite/config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get '/register_site' => 'home#register_site'
  get '/login' => 'home#login'
  get '/logout' => 'home#logout'
  
  resources :uma do
    collection do
      get 'protect_resources'
      get 'get_rpt'
      get 'check_access'
      get 'authorize_rpt'
      get 'get_gat'
    end
  end
  

end

demosite/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  	layout "application"
  	require 'resolv-replace'
  	require 'oxd-ruby'
  	protect_from_forgery with: :exception

 	before_filter :set_oxd_commands_instance
	protected
		def set_oxd_commands_instance
			@oxd_command = Oxd::ClientOxdCommands.new
		end  
end

demosite/app/controllers/home_controller.rb
class HomeController < ApplicationController
	skip_before_filter :verify_authenticity_token  

	def index	
	end

	def register_site		
		if(!@oxd_command.getOxdId.present?)			
			@oxd_command.register_site # Register site and store the returned oxd_id in config
	    end
	    authorization_url = @oxd_command.get_authorization_url
	    redirect_to authorization_url # redirect user to obtained authorization_url to authenticate
	end

	def login
		if(@oxd_command.getOxdId.present?)
			if (params[:code].present?)
				# pass the parameters obtained from callback url to get access_token
				@access_token = @oxd_command.get_tokens_by_code( params[:code]) 
    		end
	        session.delete('oxd_access_token') if(session[:oxd_access_token].present?)
        	session[:oxd_access_token] = @access_token
        	session[:state] = params[:state]
        	session[:session_state] = params[:session_state]
			@user = @oxd_command.get_user_info(session[:oxd_access_token]) # pass access_token get user information from OP
			render :template => "home/index", :locals => { :user => @user }				
		end
	end

	def logout
		# get logout url and redirect user that URL to logout from OP
		if(session[:oxd_access_token])
			@logout_url = @oxd_command.get_logout_uri(session[:oxd_access_token], session[:state], session[:session_state])
			redirect_to @logout_url
		end	    
	end
end

demosite/app/controllers/uma_controller.rb
class UmaController < ApplicationController
	skip_before_filter :verify_authenticity_token  
	require 'json'

    def index        
    end

    def protect_resources
        condition1_for_path1 = {:httpMethods => ["GET"], :scopes => ["http://photoz.example.com/dev/actions/view"]}
        condition2_for_path1 = {:httpMethods => ["PUT", "POST"], :scopes => ["http://photoz.example.com/dev/actions/all","http://photoz.example.com/dev/actions/add"], :ticketScopes => ["http://photoz.example.com/dev/actions/add"]}

        condition1_for_path2 = {:httpMethods => ["GET"], :scopes => ["http://photoz.example.com/dev/actions/view"]}

        @uma_command.uma_add_resource("/photo", condition1_for_path1, condition2_for_path1) # Add Resouyrece#1
        @uma_command.uma_add_resource("/document", condition1_for_path2) # Add Resouyrece#2
        response = @uma_command.uma_rs_protect # Register above resources with UMA RS
        render :template => "uma/index", :locals => { :protect_resources_response => response } 
    end

    def get_rpt
        rpt = @uma_command.uma_rp_get_rpt('false') # Get RPT
        render :template => "uma/index", :locals => { :rpt => rpt } 
    end

    def check_access
        response = @uma_command.uma_rs_check_access('/photo', 'GET')  # Pass the resource path and http method to check access
        render :template => "uma/index", :locals => { :check_access_response => response } 
    end

    def authorize_rpt
        response = @uma_command.uma_rp_authorize_rpt # Authorize RPT
        render :template => "uma/index", :locals => { :authorize_rpt_response => response }
    end

	def get_gat 
        scopes = ["http://photoz.example.com/dev/actions/add","http://photoz.example.com/dev/actions/view","http://photoz.example.com/dev/actions/edit"]
		gat = @uma_command.uma_rp_get_gat(scopes) # Pass scopes array to get GAT
        render :template => "uma/index", :locals => { :gat => gat } 
	end
end

demosite/app/helpers/application_helper.rb
module ApplicationHelper
end

demosite/app/views/home/index.html.erb
<div class="jumbotron">
    <h2>Ruby on Rails demo Site for OxD Ruby Library</h2>
    <p>This is a demo site showcasing the usage of OxD Ruby Library. The demo site is written in Ruby on Rails and shows that the library can be used to perform OpenID based authentication.</p>
</div>
<div class="row">
    <div class="col-md-6">
        <h3>Configuration File</h3>
        <p>Website specific configuration information is stored in a config file. This is necessary for storing persistant information like Oxd ID generated during the site registration with the Open ID provider.
        The <code>oxd_config.rb</code> shows the config file used for this demo app. The complete documentation about the config file can be obtained <a href="https://github.com/GluuFederation/oxd-ruby">here in Github</a>
        </p>
    </div>
    <div class="col-md-6">
        <h3>oxd_config.rb</h3>
        <pre class="prettyprint">
Oxd.configure do |config|
    config.oxd_host_ip                          = '127.0.0.1'
    config.oxd_host_port                        = 8099
    config.op_host                              = "https://ce-dev2.gluu.org"
    config.authorization_redirect_uri           = "https://oxd-rails.com/login"
    config.logout_redirect_uri                  = "https://oxd-rails.com/logout"
    config.post_logout_redirect_uri             = "https://oxd-rails.com/"
    config.scope                                = [ "openid", "profile" ]
    config.application_type                     = "web"
    config.client_jwks_uri                      = ""
    config.client_token_endpoint_auth_method    = ""
    config.client_request_uris                  = []
    config.contacts                             = ["example-email@gmail.com"]
    config.grant_types                          = []
    config.response_types                       = ["code"]
    config.acr_values                           = ["basic"]
    config.client_logout_uris                   = ['https://oxd-rails.com/logout']
end
        </pre>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <h3>Registration and Fetching Auth URL</h3>
        <p>The first step is to register the client with the OP. Once the client is registered, then the user data can be fetched upon user authorization.
        oxD Ruby performs client registration automatically when you request for an authorization url. Redirect the user to the authorization url to get user
        consent.</p>
        <hr>
        <p><strong> Live demo. </strong><a class="btn btn-primary" href="<%=  register_site_path %>">Go to Authorization Page</a></p>
    </div>
    <div class="col-md-6">
    <pre class="prettyprint">
def register_site
    if(!@oxd_command.getOxdId.present?)
        @oxd_command.register_site
    end
    authorization_url = @oxd_command.get_authorization_url
    redirect_to authorization_url
end
    </pre>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
    <h3>Get user information</h3>
    <p>Once the user authorizes the website to use the information from the OP, the OP calls back the website with code and scopes for accessing the user data in the registered callback <code>authorization_redirect_uri</code> in the config file. Then an access token is obtained from the OP using which user claims can be requested.</p>
    </div>
    <div class="col-md-6">
        <pre class="prettyprint">
def login
    if(@oxd_command.getOxdId.present?)
        if (params[:code].present?)
            @access_token = @oxd_command.get_tokens_by_code( params[:code])
        end
        session.delete('oxd_access_token') if(session[:oxd_access_token].present?)
        session[:oxd_access_token] = @access_token
        session[:state] = params[:state]
        session[:session_state] = params[:session_state]
        @user = @oxd_command.get_user_info(session[:oxd_access_token])  
        render :template => "home/index", :locals => { :user => @user }     
    end
end
        </pre>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <h3>Using the user claims</h3>
        <p>Once the user data is obtained, the various claims supported by the OP can be used as required.</p>
        <% if defined?(user) %>
        <div class="alert alert-success">
            <% user.each do |field,value| %>
               <%= "#{field} : #{value}" %>
               <br>
            <% end %>
        </div>
        <% else %>
            <div class="alert alert-warning">No business card for you. You haven't authorized the demo user yet.</div>
        <% end %>
    </div>
    <div class="col-md-6">
        <h3>Template code</h3>
        <pre class="prettyprint">
if defined?(user)
    &lt;div class="alert alert-success"&gt;
        user.each do |field,value|
           "#{field} : #{value}"
           &lt;br&gt;
        end
    &lt;/div&gt;
end
        </pre>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <h3>UMA Demo</h3>
        <p>UMA defines how resource owners can control protected-resource access by clients operated by arbitrary requesting parties.Once the website has been registered and authorized with OP you can register protection document with UMA.</p>
       <p><strong> Live demo. </strong><a class="btn btn-primary" href="<%= uma_index_path %>" target="_blank">Go to UMA demo page</a></p>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <h3>Logging Out</h3>
        <p>Once the required work is done the user can be logged out of the system.</p>
        <a class="btn btn-danger" href="<%= logout_path %>">Logout</a>
    </div>
   <div class="col-md-6">
    <pre class="prettyprint">
def logout
    if(session[:oxd_access_token])
        @logout_url = @oxd_command.get_logout_uri(session[:oxd_access_token], session[:state], session[:session_state])
        redirect_to @logout_url
    end    
end
    </pre>
    </div>
</div>

demosite/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Oxdrails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>

demosite/app/views/uma/index.html.erb
<div class="jumbotron">
    <h2>UMA RS and UMA RP Demo page for OxD Ruby Library</h2>
</div>

<div class="row">
    <div class="col-md-6">
        <h3>UMA RS Protect resources</h3>
        <p>To protect resources with UMA RS, you need to add resources to library using <code>uma_add_resource(path, *conditions)</code> method. Then you can call <code>uma_rs_protect</code> method to register resources for protection with UMA RS.</p>
        <p><strong> Live demo. </strong><a class="btn btn-primary" href="<%=   protect_resources_uma_index_path  %>">Protect Resources</a></p>
        <% if defined?(protect_resources_response) %>
        <div class="alert alert-success">
            <%= "Response Oxd ID: #{protect_resources_response}" %>
        </div>
        <% end %>
    </div>
    <div class="col-md-6">
    <pre class="prettyprint">
def protect_resources
    condition1 = {:httpMethods => ["GET"], :scopes => ["http://photoz.example.com/dev/actions/view"]}
    condition2 = {:httpMethods => ["PUT", "POST"], 
                :scopes => ["http://photoz.example.com/dev/actions/all","http://photoz.example.com/dev/actions/add"], 
                :ticketScopes => ["http://photoz.example.com/dev/actions/add"]
            }
    @uma_command.uma_add_resource("/photo", condition1, condition2)
    @uma_command.uma_rs_protect
end
    </pre>
    </div>
</div>
<hr>
<div class="row">
    <div class="col-md-6">
        <h3>UMA RP - Get RPT</h3>
        <p>To gain access to protected resources at the UMA resource server, you must first obtain RPT (Requesting Party Token) using <code>uma_rp_get_rpt(force_new)</code> call.</p>
        <p><strong> Live demo. </strong><a class="btn btn-primary" href="<%=  get_rpt_uma_index_path %>">Get RPT</a></p>        
        <% if defined?(rpt) %>
        <div class="alert alert-success">
            <%= "Response RPT is: #{rpt}" %>
        </div>
        <% end %>
    </div>
    <div class="col-md-6">
        <pre class="prettyprint">
def get_rpt
    rpt = @uma_command.uma_rp_get_rpt(false)
    render :template => "uma/index", :locals => { :rpt => rpt } 
end
        </pre>
    </div>
</div>
<hr>
<div class="row">
    <div class="col-md-6">
    <h3>UMA RS Check Access</h3>
    <p>To check wether you have access to a particular resource on UMA Resource Sevrer or not, make call to <code>uma_rs_check_access(path, http_method)</code> method.</p>
    <p><strong> Live demo. </strong><a class="btn btn-primary" href="<%=  check_access_uma_index_path %>">Check access</a></p>
    <% if defined?(check_access_response) %>
        <% if check_access_response['access'] == 'denied' %>
            <div class="alert alert-warning">
                <%= "Response : access #{check_access_response['access']}" %><br>
                <%= "Response ticket : #{check_access_response['ticket']}" if check_access_response['ticket'].present? %>
            </div>
        <% else %>
            <div class="alert alert-success">
                <%= "Response : #{check_access_response}" %>
            </div>
        <% end %>    
    <% end %>
    </div>
    <div class="col-md-6">
    	<pre class="prettyprint">
def check_access
    response = @uma_command.uma_rs_check_access('/photo', 'GET')
    render :template => "uma/index", :locals => { :check_access_response => response } 
end
		</pre>
    </div>
</div>
<hr>
<div class="row">
    <div class="col-md-6">
        <h3>UMA RP - Authorize RPT</h3>
        <p>You must first get RPT (refer to 'Get RPT' section) before authorizing. If you have already obtained the RPT, use <code>uma_rp_authorize_rpt</code> method provided by oxd-ruby library to authorize RPT.</p>
       <p><strong> Live demo. </strong><a class="btn btn-primary" href="<%=  authorize_rpt_uma_index_path %>">Authorize RPT</a></p>
       <% if defined?(authorize_rpt_response) %>
        <div class="alert alert-success">
            <%= "Response Oxd ID: #{authorize_rpt_response}" %>
        </div>
        <% end %>
    </div>
    <div class="col-md-6">
        <pre class="prettyprint">
def authorize_rpt
    response = @uma_command.uma_rp_authorize_rpt
    render :template => "uma/index", :locals => { :authorize_rpt_response => response }
end
        </pre>
    </div>
</div>
<hr>
<div class="row">
    <div class="col-md-6">
        <h3>UMA RP - Get GAT</h3>
        <p>To obtain GAT(Gluu Access Token) call to <code>uma_rp_get_gat(scopes)</code> method with scopes as parameter.</p>
        <p><strong> Live demo. </strong><a class="btn btn-primary" href="<%=  get_gat_uma_index_path %>">Get GAT</a></p>
        <% if defined?(gat) %>
        <div class="alert alert-success">
            <%= "Response GAT is: #{gat}" %>
        </div>
        <% end %>
    </div>
   <div class="col-md-6">
    <pre class="prettyprint">
def get_gat 
    scopes = ["http://photoz.example.com/dev/actions/add","http://photoz.example.com/dev/actions/view","http://photoz.example.com/dev/actions/edit"]
    gat = @uma_command.uma_rp_get_gat(scopes)
    render :template => "uma/index", :locals => { :gat => gat } 
end
    </pre>
    </div>
</div>